#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

#!/bin/bash

# Check Vault version
echo "Check: Vault version"
vault_version=$(vault version | awk '{print $2}')
if [[ "$vault_version" != "v1.13.0" ]]; then
  echo "Vault version is incorrect"
  exit 1
fi

# Check Vault status
echo "Check: Vault Status"
vault_status=$(vault status |grep Sealed |awk '{print $2}')

if [[ "$vault_status" != "false" ]]; then
  echo "Vault is not running"
  exit 1
fi

exit 0
