#!/bin/bash
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#
#set -x # Uncomment to Debug

# Start Vault in dev mode with root token
echo "Starting vault in dev mode"
vault server -dev -dev-root-token-id=root -dev-listen-address=vault-server:8200 &

exit 0
