#!/bin/bash
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#
# set -x # Uncomment to Debug

# Output from this script is redirected to /tmp/setup.out
# exec > >(tee -i /tmp/setup.out)
echo "Starting Setup Script"

echo "Waiting for bootstrap to complete"
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
  echo "Waiting for bootstrap to complete"
    sleep 1
done

echo "Waiting for vault token to be available"
until [ ! -z "$VAULT_TOKEN" ]; do
  echo "Waiting for vault token to be available"
    sleep 1
done

echo "Starting vault in dev mode"
systemctl daemon-reload
systemctl start vault
systemctl enable vault

sleep 10

exit 0