#!/bin/bash
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "Solving the challenge by loading a default k/v pair into vault"

export user="Dan Fedick"
export age="45"
vault kv put secret/info name="${user}" age="${age}"
exit 0
