#!/bin/bash
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

#/usr/local/bin/vault server -dev -dev-root-token-id=${VAULT_TOKEN} -dev-listen-address=0.0.0.0:8200 &

# Variables
echo "Setting up variables"
export user="Dan Fedick"
export age="45"

echo "Solving the challenge by loading a default k/v pair into vault"
/usr/local/bin/vault kv put secret/info name="${user}" age="${age}"

exit 0
