#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

export VAULT_ADDR=http://127.0.0.1:8200
export VAULT_TOKEN=root

vault auth enable aws

vault write auth/aws/config/client \
 access_key="$AWS_ACCESS_KEY_ID" \
 secret_key="$AWS_SECRET_ACCESS_KEY" \
 region=us-west-2

exit 0
