#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

#!/bin/bash

# Is Data loaded into the database? 
echo "Check: Ensure data is loaded into the database"
echo "Counting records in user database"

count=$(sudo -u postgres psql -d users  -c "select count(*) from users;" |grep 50 |awk '{print $1}')
echo "Count: $count"

if [[ "$count" != "50"  ]]; then
  echo "Data is not loaded into the database"
  exit 1
fi

exit 0