#!/bin/bash
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#
echo "Check to see if Postgres is running"

postgres_stat=$(service postgresql status |awk '{print $NF}')

if [[ $postgres_stat != "online" ]]; then
    echo "Postgres is not running"
    service postgresql start
    echo "Starting Postgresql"
fi

cat << EOF > /etc/dataview.yml
---
username: "postgres"
password: "postgres"
host: "app-server"
port: 5432
dbName: "users"
webPort: 8888
EOF


exit 0
