#!/bin/bash
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "Starting Postgres"
service postgresql start

echo "Starting Dataview"
systemctl start dataview

exit 0
