version: "3"
containers:
- name: vault-server
  image: ubuntu
  shell: /bin/bash
  memory: 256
  environment:
    VAULT_ADDR: http://vault-server:8200
- name: app-server
  image: ubuntu
  shell: /bin/bash
  memory: 256
  environment:
    VAULT_ADDR: http://vault-server:8200
    PGPASSWORD: postgres
    PGUSER:  postgres
    PGDB: users
    PGHOST: app-server
    PGPORT: 5432
aws_accounts:
- name: awsaccount