version: "3"
containers:
- name: vault-server
  image: danfedick/vault-server:latest
  shell: /bin/bash
  memory: 512
  environment:
    VAULT_ADDR: http://vault-server:8200
    VAULT_TOKEN: root
    HOSTNAME: vault-server
- name: app-server
  image: danfedick/app-server:latest
  shell: /bin/bash
  memory: 512
  environment:
    VAULT_ADDR: http://vault-server:8200
    VAULT_TOKEN: root
    HOSTNAME: app-server
    PGPASSWORD: postgres
    PGUSER:  postgres
    PGDB: users
    PGHOST: app-server
    PGPORT: 5432
- name: consul-server
  image: danfedick/consul-server:latest
  shell: /bin/bash
  memory: 512
  environment:
    VAULT_ADDR: http://vault-server:8200
    VAULT_TOKEN: root
    CONSUL_DATA_DIR: /etc/consul.d/data
    CONSUL_CONFIG_DIR: /etc/consul.d
aws_accounts:
- name: awsaccount
  managed_policies: ["arn:aws:iam::aws:policy/AdministratorAccess"]
