#!/bin/bash
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#
#set -x # Uncomment to Debug


# Start Postgres Database
echo "Setup: Start Postgres Database"
service postgresql start


