#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the solve script"
# Load data into database
/usr/local/bin/dataload -hostname $HOSTNAME -database $PGDB  -port $PGPORT -file /tmp/users.json -password $PGPASSWORD
exit 0
