# 
FROM ubuntu:20.04

# Install required packages
RUN apt-get update
RUN apt-get install -y unzip curl wget jq sudo systemctl inetutils-ping

# Install Vault
ENV VAULT_VERSION=1.13.0
WORKDIR /tmp
RUN wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
RUN unzip vault_${VAULT_VERSION}_linux_amd64.zip
RUN mv vault /usr/local/bin/
RUN chmod -R 755 /usr/local/bin/vault
COPY lab-zero-trust/assets/containers/vault.service /etc/systemd/system/vault.service