#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "Check: Consul configuration directory exists"
if [[ -d /etc/consul.d ]]; then
  echo "Consul configuration directory exists"
else
  echo "Consul configuration directory does not exist"
  exit 1
fi

echo "Check: Does the Consul Gossip file exist?"
if [[ -f /etc/consul.d/consul-gossip-encryption.hcl ]]; then
  echo "Consul Gossip file exists"
else
  echo "Consul Gossip file does not exist"
  exit 1
fi

echo "Check Consul TLS Certs are created:" 
if [[ -f /etc/consul.d/certs/dc1-server-opengov.co-0.pem ]] && [[ -f /etc/consul.d/certs/dc1-server-opengov.co-0-key.pem ]] && [[ -f /etc/consul.d/certs/opengov.co-agent-ca.pem ]] && [[ -f /etc/consul.d/certs/opengov.co-agent-ca-key.pem ]]; then
  echo "Consul TLS Certs are created"
else
  echo "Consul TLS Certs are not created"
  exit 1
fi

echo "Check: Does Server file exist and has content?"
if [[ -f /etc/consul.d/server.hcl ]] && [[ -s /etc/consul.d/server.hcl ]]; then
  echo "Server file exists and has the following content:"
  cat /etc/consul.d/server.hcl
else
  echo "Server file does not exist"
  exit 1
fi

echo "Check: Is Consul Service running?"
CONSUL_STAT=$(systemctl status consul  |grep Active: |awk '{print $2}')
if [[ $CONSUL_STAT == "active" ]]; then
  echo "Consul Service is running"
else
  echo "Consul Service is not running"
  exit 1
fi

exit 0
