#!/bin/bash
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

export DOMAIN="opengov.co"
export NODENAME="consul-server"
export DATACENTER="dc1"
export CONSUL_CONFIG_DIR="/etc/consul.d"
export CONSUL_CERT_DIR="/etc/consul.d/certs"

mkdir -p ${CONSUL_CONFIG_DIR}/certs ${CONSUL_CONFIG_DIR}/logs ${CONSUL_CONFIG_DIR}/data
set-workdir ${CONSUL_CONFIG_DIR}

echo "Create Consul Server Startup Script"

cat << EOF > /etc/systemd/system/consul.service
[Unit]
Description="HashiCorp Consul - A service mesh solution"
Documentation=https://www.consul.io/
Requires=network-online.target
After=network-online.target

[Service]
User=consul
Group=consul
ExecStart=/usr/local/bin/consul agent -config-dir=${CONSUL_CONFIG_DIR}
ExecReload=/bin/kill --signal HUP \$MAINPID
KillMode=process
KillSignal=SIGTERM
Restart=on-failure
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl stop consul.service

exit 0
