#!/bin/bash
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "Start Dataview and Vault Agent"
systemctl start vault-agent 

sleep 2
systemctl start dataview
sleep 2

exit 0
