#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "Check to see if Postgres is running"
postgres_stat=$(service postgresql status |awk '{print $NF}')
if [[ $postgres_stat != "online" ]]; then
    echo "Postgres is not running"
    exit 1
fi

echo "Check to see if Dataview is installed"
if [[ ! -f /usr/local/bin/dataview ]]; then
    echo "DataView server is not installed"
    exit 1
fi

echo "Check if dataview is running and getting 200 response"

stat=$(curl -s -o /dev/null -w "%{http_code}" http:/app-server:8888)
if [[ $stat -ne 200 ]]; then
    echo "Dataview server is not running"
    exit 1
fi

exit 0
