#!/bin/bash
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
# exec > >(tee -i /tmp/setup.out)

echo "This is the setup script"

echo "Running Vault Status Command"
vault status

echo "Creating a dataview code directory"
mkdir -p /root/dataview

echo "Place Dataview Vault Policy File"
cat << EOF > /root/dataview/dataview-policy.hcl
# Allow a token to renew itself
path "auth/token/renew-self" {
  capabilities = ["update"]
}

# Add list of leases presently applicable to any mount
path "sys/leases/lookup" {
  capabilities = ["list"]
}

# List accessor IDs of all generated tokens present in the Vault
path "auth/token/accesors" {
    capabilities = ["list"]
}

# Dataview Policy
path "database/creds/dataview" {
  capabilities = ["read", "list"]
}

EOF

exit 0
