#!/bin/bash
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "Solve: Enable AWS Auth Backend in Vault"
vault auth enable aws

echo "Solve: Configure AWS Auth Backend in Vault"
vault write auth/aws/config/client \
 access_key="$AWS_ACCESS_KEY_ID" \
 secret_key="$AWS_SECRET_ACCESS_KEY" \
 region=us-west-2

echo "Create dataview policy"
vault policy write dataview /root/dataview/dataview-policy.hcl

echo "Solve: Configure the dataview role. Tie to the dataview policy and set the max_ttl to 1h"
vault write auth/aws/role/dataview \
  auth_type=iam \
  policies=dataview \
  max_ttl=1h \
  bound_iam_principal_arn="arn:aws:iam::$AWS_ACCOUNT_ID:*"

exit 0
